version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    container_name: material-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gotham
    ports:
      - '5432:5432'
    volumes:
      - './postgres/data:/var/lib/postgresql/data'